### PR TITLE
Fix conditions in while loops

### PR DESCRIPTION
**Pull request by fcard**
Hello again!
I was experimenting with this again and noticed that while loops weren't working, so here.

### CODE REVIEW

**Comment by coderofsalvation** [comment]
Thx!
Btw. have you seen my 'while'-commit? 
Should we still merge this?

**Comment by fcard** [comment]
Your version has a bug:

``` shell
i=0
while $i < 10
  echo $i
  i=$(math "$i+1")
```

transpiles to:

```
while $i < 10; do # needs brackets, plus < should be -lt
  echo "$i"
  i=$(math "$i+1")
done
```

I got the same problem at first, which is why I refactored the `if`code into two parts here, so I could reuse the checks for when brackets are necessary in the while loop.
What about those changes to `getindent` and `transpile_for`? Are they related?
Other than that we did the same thing :P

**Comment by fcard** [comment]
I re-purposed this PR so it mixes both our codes to fix the above bug.

**Comment by coderofsalvation** [comment]
thanks
This looks totally mergable.
Btw. just curious. Why do you think brackets are needed for while-loops?
Never used brackets for while loops.

**Comment by fcard** [comment]
@coderofsalvation It needs brackets in the same situations where `if` does, e.g. if you try:

``` shell
i=1
while $i -lt 10; do
  echo "$i"
  i=$(math "$i+1")
done
```

You get `1: command not found`.
Conditions always need them brackets. (posix = one bracket, bash extensions = two)

**Comment by fcard** [comment]
Or do you mean, if there are any situations where these types of conditions are needed in while loops? (sorry if I assumed you didn't know that when you did, it was a reflex explanation :P I actually haven't spoken much to programmers other than students)

I mean, I feel while loops would be limited without support for general conditions. This way it also behaves more like it does in other languages.

Although now that you said it, I haven't used it this way much either. (although, that might just be because of how annoying it's to deal with arrays in bash, maybe in powscript it would be more prevalent?)

**Comment by coderofsalvation** [comment]
ah you mean the square brackets, no worries, I was confused.
Merging! thanks!

**Pull request merged**
