### PR TITLE
Disable automatic quoting when already inside quotes

### PR DESCRIPTION
**Pull request by fcard**
Also autoquote parens interpolation. (`${x}`, `$(x)`, ...)

---
This changes the `sed` call to a more traditional parsing algorithm. This isn't a problem that can be solved by regexes unfortunately (grammars and whatnot), but despite being a lot more code it should actually be a bit faster.  We can probably move some more logic there later to remove extra passes and make that chunk of code more significant :P

Also @coderofsalvation, could you explain what the `$NO_QUOTES` variable is for? No tests fail without it, so an example of the bug it's solving would be nice.

### CODE REVIEW

**Comment by fcard** [comment]
:musical_note:  :musical_note: :musical_note: How is it going? :musical_note:

**Comment by coderofsalvation** [comment]
Hi,

I totally overlooked this PR since I'm currently swamped with work. 
I gave you commit rights so you can just merge minor commits like this.
Can we agree on still doing PR's for >10 line-commits (you can merge them If I'm not responsive enough) :)

**Comment by fcard** [comment]
I am cool with that! I will re-review this code since it's been a while, fix the conflicts and merge.

I have some more changes in the backlog I want to commit but I blew up my linux last week and am still cleaning the mess, so that might take a week or two ;P

Good luck with your work!

**Comment by coderofsalvation** [comment]
hehe I know what you mean.
Once a year i burn myself while 'upgrading' my whole linux distro :1st_place_medal:

**Comment by fcard** [comment]
Ready to go I think, you already green-lighted this so lets put these commit rights to use and merge the sucker. **\*stretches fingers\* \*cracks knuckles\***

**Pull request merged**
